SEASON = "2020/21"

METRICS_TO_INVERT = ['Offside Passes', 'Out-of-bound Passes', 'Passes Intercepted', 'Passes Blocked', 
					 'Unsuccessful Tackles vs Dribblers', 'Errors', 'Times Misplaced', 'Times Dispossessed',
					 'Yellow Cards', 'Red Cards', 'Second Yellow Cards', 'Fouls Committed', 'Offsides',
					 'Penalties Conceded', 'Own-goals', 'Aerial Duels Lost', 'Turnovers']

POSITIONS_DICT =    {'DM/CM': 'Central Midfielders',
                               'CAM/WF': 'Attacking Midfielders/Wide Attackers',
                               'FB': 'Fullbacks',
                               'CB': 'Centre Backs',
                               'FW': 'Forwards'
                              }
                              
POSITIONS_FBREF_DICT =    {'DM/CM': 'MF',
                               'CAM/WF': 'FW',
                               'FB': 'DF',
                               'CB': 'DF',
                               'FW': 'FW'
                              }

POSITIONS_COLORS_DICT = {'DM/CM': 'darkorange',
                         'CAM/WF': 'darkmagenta',
                         'FB': 'darkcyan',
                         'CB': 'limegreen',
                         'FW': 'dodgerblue'}                                                            

URLS_DICT = {'shooting': "https://fbref.com/en/comps/189/shooting/Womens-Super-League-Stats",
                    'passing': "https://fbref.com/en/comps/189/passing/Womens-Super-League-Stats",
                    'pass_types': "https://fbref.com/en/comps/189/passing_types/Womens-Super-League-Stats",
                    'gca_sca': "https://fbref.com/en/comps/189/gca/Womens-Super-League-Stats",
                    'def_actions': "https://fbref.com/en/comps/189/defense/Womens-Super-League-Stats",
                    'possession':"https://fbref.com/en/comps/189/possession/Womens-Super-League-Stats",
                    'misc_stats': "https://fbref.com/en/comps/189/misc/Womens-Super-League-Stats"
                    }

COLUMNS_KEY  = {    "Player": "Player", 
					"Nation": "Nation", 
					"Pos": "Pos", 
					"Squad": "Squad", 
					"Comp": "Comp", 
					"Age": "Age", 
					"90s": "90s", 
					"Gls": "Goals",
                    "Standard_Gls": "Goals",
					"Standard_Sh": "Shots", 
					"Standard_SoT": "Shots on Target", 
					"Standard_SoT%": "Shots on Target %", 
					"Standard_Dist": "Average Shot Distance", 
					"Standard_FK": "Freekicks Attempted", 
                    "Performance_PK": "Penalties Scored", 
                    "Standard_PKatt": "Penalties Attempted", 
					"Expected_xG": "xG", 
					"Non-penalty Goals": "Non-penalty Goals",
					"Expected_npxG": "Non-penalty xG", 
					"Expected_npxG/Sh": "Non-penalty xG/shot", 
					"Expected_G-xG": "Goals - xG", 
					"Expected_np:G-xG": "Non-penalty Goals - Non-penalty xG", 
					"Total_Cmp": "Passes Completed", 
					"Total_Att": "Passes Attempted", 
					"Total_Cmp%": "Pass Completion %", 
					"Total_TotDist": "Passing Distance", 
					"Total_PrgDist": "Progressive Passing Distance", 
					"Short_Cmp": "Short Passes Completed", 
					"Short_Att": "Short Passes Attempted", 
					"Short_Cmp%": "Short Pass Completion %", 
					"Medium_Cmp": "Medium Passes Completed", 
					"Medium_Att": "Medium Passes Attempted", 
					"Medium_Cmp%": "Medium Pass Completion %", 
					"Long_Cmp": "Long Passes Completed", 
					"Long_Att": "Long Passes Attempted", 
					"Long_Cmp%": "Long Pass Completion %", 
					"Ast": "Assists", 
					"xA": "xA", 
					"A-xA": "Assists - xA", 
					"KP": "Key Passes", 
					"1/3": "Passes into Final Third", 
					"PPA": "Passes into Penalty Area", 
					"CrsPA": "Crosses into Penalty Area", 
					"Prog": "Progressive Passes Completed", 
					"Pass Types_Live": "Open-play Passes", 
					"Pass Types_Dead": "Dead-ball Passes", 
					"Pass Types_FK": "Free-kick Passes", 
					"Pass Types_TB": "Throughballs", 
					"Pass Types_Press": "Passes under Pressure", 
					"Pass Types_Sw": "Switches", 
					"Pass Types_Crs": "Crosses", 
					"Pass Types_CK": "Corner Kicks", 
					"Corner Kicks_In": "Inswinging Corners", 
					"Corner Kicks_Out": "Outswinging Corners", 
					"Corner Kicks_Str": "Straight Corners", 
					"Height_Ground": "Ground Passes", 
					"Height_Low": "Low Passes", 
					"Height_High": "High Passes", 
					"Body Parts_Left": "Passes from Left Foot", 
					"Body Parts_Right": "Passes from Right Foot", 
					"Body Parts_Head": "Headed Passes", 
					"Body Parts_TI": "Throw-ins Taken", 
					"Body Parts_Other": "Passes from Other Bodypart", 
					"Outcomes_Cmp": "Passes Completed", 
					"Outcomes_Off":"Offside Passes", 
					"Outcomes_Out": "Out-of-bound Passes", 
					"Outcomes_Int": "Passes Intercepted", 
					"Outcomes_Blocks": "Passes Blocked", 
					"SCA_SCA": "Shot-creating Actions", 
					"SCA Types_PassLive": "Open-play Shot-creating Passes", 
					"SCA Types_PassDead": "Dead-ball Shot-creating Actions", 
					"SCA Types_Drib": "Shot-creating Dribbles", 
					"SCA Types_Sh": "Shot-creating Shots", 
					"SCA Types_Fld": "Shot-creating Actions Fouls Drawn", 
					"SCA Types_Def": "Shot-creating Defensive Actions", 
					"GCA_GCA": "Goal-creating Actions", 
					"GCA Types_PassLive": "Open-play Goal-creating Passes", 
					"GCA Types_PassDead": "Dead-ball Goal-creating Actions", 
					"GCA Types_Drib": "Goal-creating Dribbles", 
					"GCA Types_Sh": "Goal-creating Shots", 
					"GCA Types_Fld": "Goal-creating Fouls Drawn", 
					"GCA Types_Def": "Goal-creating Defensive Actions", 
					"GCA Types_OG": "Action leading to Opposition Own-goal", 
					"Tackles_Tkl": "Tackles Attempted", 
					"Tackles_TklW": "Tackles Won", 
					"Tackles_Def 3rd": "Defensive Third Tackles", 
					"Tackles_Mid 3rd": "Middle Third Tackles", 
					"Tackles_Att 3rd": "Final Third Tackles", 
					"Vs Dribbles_Tkl": "Successful Tackles vs Dribblers", 
					"Vs Dribbles_Att": "Attempted Tackles vs Dribblers", 
					"Vs Dribbles_Tkl%": "Tackle success % vs Dribblers", 
					"Vs Dribbles_Past": "Unsuccessful Tackles vs Dribblers", 
					"Pressures_Press": "Pressures", 
					"Pressures_Succ": "Successful Pressures", 
					"Pressures_%": "Pressure Success %", 
					"Pressures_Def 3rd": "Defensive Third Pressures", 
					"Pressures_Mid 3rd": "Middle Third Pressures", 
					"Pressures_Att 3rd": "Final Third Pressures", 
					"Blocks_Blocks": "Blocks", 
					"Blocks_Sh": "Shots Blocked", 
					"Blocks_ShSv": "Shot on Target Blocked", 
					"Blocks_Pass": "Passes Blocked", 
					"Int": "Interceptions",
                    "Int_x": "Interceptions", 
					"Clr": "Clearances", 
					"Err": "Errors", 
					"Turnovers": "Turnovers", 
					"Open-play SCA": "Open-play Shot-creating Actions",
					"Touches_Touches": "Touches", 
					"Touches_Def Pen": "Touches in Own Penalty Area", 
					"Touches_Def 3rd": "Touches in Defensive Third", 
					"Touches_Mid 3rd": "Touches in Middle Third", 
					"Touches_Att 3rd": "Touches in Attacking Third", 
					"Touches_Att Pen": "Touches in Penalty Area", 
					"Touches_Live": "Open-play Touches", 
					"Dribbles_Succ": "Successful Dribbles", 
					"Dribbles_Att": "Attempted Dribbles", 
					"Dribbles_Succ%": "Dribble Success %", 
					"Dribbles_#Pl": "Number of Players Dribbled", 
					"Dribbles_Megs": "Nutmegs", 
					"Carries_Carries": "Carries", 
					"Carries_TotDist": "Total Distance Carried", 
					"Carries_PrgDist": "Progressive Distance Carried", 
					"Carries_Prog": "Progressive Carries", 
					"Carries_1/3": "Carries into Final Third", 
					"Carries_CPA": "Carries into Penalty Area", 
					"Carries_Mis": "Times Misplaced", 
					"Carries_Dis": "Times Dispossessed", 
					"Receiving_Targ": "Attempted Ball Receipts", 
					"Receiving_Rec": "Successful Ball Receipts", 
					"Receiving_Rec%": "Successful Ball Receipt %", 
					"Receiving_Prog": "Progressive Passes Received", 
					"Performance_CrdY": "Yellow Cards", 
					"Performance_CrdR": "Red Cards", 
					"Performance_2CrdY": "Second Yellow Cards", 
					"Performance_Fls": "Fouls Committed", 
					"Performance_Fld": "Fouls Drawn", 
					"Performance_Off": "Offsides", 
					"Performance_Crs": "Crosses", 
					"Performance_Int": "Interceptions",
					"Performance_TklW": "Tackles Won", 
					"Performance_PKwon": "Penalties Won", 
					"Performance_PKcon": "Penalties Conceded", 
					"Performance_OG": "Own-goals", 
					"Performance_Recov": "Recoveries", 
					"Aerial Duels_Won": "Aerial Duels Won", 
					"Aerial Duels_Lost": "Aerial Duels Lost", 
					"Aerial Duels_Won%": "Aerial Duels Success %"
}

UNCLEAN_COLUMNS_DICT ={
'shooting':[
            ( 'Unnamed: 1_level_0',  'Player'),
            ( 'Unnamed: 2_level_0',  'Nation'),
            ( 'Unnamed: 3_level_0',     'Pos'),
            ( 'Unnamed: 4_level_0',   'Squad'),
            ( 'Unnamed: 5_level_0',    'Comp'),
            ( 'Unnamed: 6_level_0',     'Age'),
            ( 'Unnamed: 8_level_0',     '90s'),
            (           'Standard',     'Gls'),
            (           'Standard',      'Sh'),
            (           'Standard',     'SoT'),
            (           'Standard',    'SoT%'),
            (           'Standard',   'Sh/90'),
            (           'Standard',  'SoT/90'),
            (           'Standard',    'G/Sh'),
            (           'Standard',   'G/SoT'),
            (           'Standard',    'Dist'),
            (           'Standard',      'FK'),
            (           'Standard',      'PK'),
            (           'Standard',   'PKatt'),
            (           'Expected',      'xG'),
            (           'Expected',    'npxG'),
            (           'Expected', 'npxG/Sh'),
            (           'Expected',    'G-xG'),
            (           'Expected', 'np:G-xG')
            ],

'passing': [
            ( 'Unnamed: 1_level_0',  'Player'),
            ( 'Unnamed: 4_level_0',   'Squad'),
            ( 'Unnamed: 5_level_0',    'Comp'),
            ( 'Unnamed: 6_level_0',     'Age'),
            (              'Total',     'Cmp'),
            (              'Total',     'Att'),
            (              'Total',    'Cmp%'),
            (              'Total', 'TotDist'),
            (              'Total', 'PrgDist'),
            (              'Short',     'Cmp'),
            (              'Short',     'Att'),
            (              'Short',    'Cmp%'),
            (             'Medium',     'Cmp'),
            (             'Medium',     'Att'),
            (             'Medium',    'Cmp%'),
            (               'Long',     'Cmp'),
            (               'Long',     'Att'),
            (               'Long',    'Cmp%'),
            ('Unnamed: 23_level_0',     'Ast'),
            ('Unnamed: 24_level_0',      'xA'),
            ('Unnamed: 25_level_0',    'A-xA'),
            ('Unnamed: 26_level_0',      'KP'),
            ('Unnamed: 27_level_0',     '1/3'),
            ('Unnamed: 28_level_0',     'PPA'),
            ('Unnamed: 29_level_0',   'CrsPA'),
            ('Unnamed: 30_level_0',    'Prog')
            ],
'pass_types': [
            ( 'Unnamed: 1_level_0',  'Player'),
            ( 'Unnamed: 4_level_0',   'Squad'),
            ( 'Unnamed: 5_level_0',    'Comp'),
            ( 'Unnamed: 6_level_0',     'Age'),
            (         'Pass Types',    'Live'),
            (         'Pass Types',    'Dead'),
            (         'Pass Types',      'FK'),
            (         'Pass Types',      'TB'),
            (         'Pass Types',   'Press'),
            (         'Pass Types',      'Sw'),
            (         'Pass Types',     'Crs'),
            (         'Pass Types',      'CK'),
            (       'Corner Kicks',      'In'),
            (       'Corner Kicks',     'Out'),
            (       'Corner Kicks',     'Str'),
            (             'Height',  'Ground'),
            (             'Height',     'Low'),
            (             'Height',    'High'),
            (         'Body Parts',    'Left'),
            (         'Body Parts',   'Right'),
            (         'Body Parts',    'Head'),
            (         'Body Parts',      'TI'),
            (         'Body Parts',   'Other'),
            (           'Outcomes',     'Cmp'),
            (           'Outcomes',     'Off'),
            (           'Outcomes',     'Out'),
            (           'Outcomes',     'Int'),
            (           'Outcomes',  'Blocks')
            ],
'gca_sca': [
            ( 'Unnamed: 1_level_0',   'Player'),
            ( 'Unnamed: 4_level_0',    'Squad'),
            ( 'Unnamed: 5_level_0',     'Comp'),
            ( 'Unnamed: 6_level_0',      'Age'),
            (                'SCA',      'SCA'),
            (          'SCA Types', 'PassLive'),
            (          'SCA Types', 'PassDead'),
            (          'SCA Types',     'Drib'),
            (          'SCA Types',       'Sh'),
            (          'SCA Types',      'Fld'),
            (          'SCA Types',      'Def'),
            (                'GCA',      'GCA'),
            (          'GCA Types', 'PassLive'),
            (          'GCA Types', 'PassDead'),
            (          'GCA Types',     'Drib'),
            (          'GCA Types',       'Sh'),
            (          'GCA Types',      'Fld'),
            (          'GCA Types',      'Def'),
            (          'GCA Types',       'OG')
            ],
'def_actions': [
            ( 'Unnamed: 1_level_0',  'Player'),
            ( 'Unnamed: 4_level_0',   'Squad'),
            ( 'Unnamed: 5_level_0',    'Comp'),
            ( 'Unnamed: 6_level_0',     'Age'),
            (            'Tackles',     'Tkl'),
            (            'Tackles',    'TklW'),
            (            'Tackles', 'Def 3rd'),
            (            'Tackles', 'Mid 3rd'),
            (            'Tackles', 'Att 3rd'),
            (        'Vs Dribbles',     'Tkl'),
            (        'Vs Dribbles',     'Att'),
            (        'Vs Dribbles',    'Tkl%'),
            (        'Vs Dribbles',    'Past'),
            (          'Pressures',   'Press'),
            (          'Pressures',    'Succ'),
            (          'Pressures',       '%'),
            (          'Pressures', 'Def 3rd'),
            (          'Pressures', 'Mid 3rd'),
            (          'Pressures', 'Att 3rd'),
            (             'Blocks',  'Blocks'),
            (             'Blocks',      'Sh'),
            (             'Blocks',    'ShSv'),
            (             'Blocks',    'Pass'),
            ('Unnamed: 28_level_0',     'Int'),
            ('Unnamed: 29_level_0', 'Tkl+Int'),
            ('Unnamed: 30_level_0',     'Clr'),
            ('Unnamed: 31_level_0',     'Err')
            ],
'possession': [
            ( 'Unnamed: 1_level_0',  'Player'),
            ( 'Unnamed: 4_level_0',   'Squad'),
            ( 'Unnamed: 5_level_0',    'Comp'),
            ( 'Unnamed: 6_level_0',     'Age'),
            (            'Touches', 'Touches'),
            (            'Touches', 'Def Pen'),
            (            'Touches', 'Def 3rd'),
            (            'Touches', 'Mid 3rd'),
            (            'Touches', 'Att 3rd'),
            (            'Touches', 'Att Pen'),
            (            'Touches',    'Live'),
            (           'Dribbles',    'Succ'),
            (           'Dribbles',     'Att'),
            (           'Dribbles',   'Succ%'),
            (           'Dribbles',     '#Pl'),
            (           'Dribbles',    'Megs'),
            (            'Carries', 'Carries'),
            (            'Carries', 'TotDist'),
            (            'Carries', 'PrgDist'),
            (            'Carries',    'Prog'),
            (            'Carries',     '1/3'),
            (            'Carries',     'CPA'),
            (            'Carries',     'Mis'),
            (            'Carries',     'Dis'),
            (          'Receiving',    'Targ'),
            (          'Receiving',     'Rec'),
            (          'Receiving',    'Rec%'),
            (          'Receiving',    'Prog')
            ],
'misc_stats': [
            ( 'Unnamed: 1_level_0',  'Player'),
            ( 'Unnamed: 4_level_0',   'Squad'),
            ( 'Unnamed: 5_level_0',    'Comp'),
            ( 'Unnamed: 6_level_0',     'Age'),
            (        'Performance',    'CrdY'),
            (        'Performance',    'CrdR'),
            (        'Performance',   '2CrdY'),
            (        'Performance',     'Fls'),
            (        'Performance',     'Fld'),
            (        'Performance',     'Off'),
            (        'Performance',     'Crs'),
            (        'Performance',     'Int'),
            (        'Performance',    'TklW'),
            (        'Performance',   'PKwon'),
            (        'Performance',   'PKcon'),
            (        'Performance',      'OG'),
            (        'Performance',   'Recov'),
            (       'Aerial Duels',     'Won'),
            (       'Aerial Duels',    'Lost'),
            (       'Aerial Duels',    'Won%')
            ]
 }

NUMERIC_COLUMNS = ['90s', 'Goals', 'Shots', 'Shots on Target', 'Shots on Target %',
                'Average Shot Distance', 'Freekicks Attempted', 'Penalties Scored', 'Penalties Attempted',
                'xG', 'Non-penalty xG', 'Non-penalty xG/shot', 'Goals - xG',
			    'Non-penalty Goals - Non-penalty xG', 'Passes Completed', 'Passes Attempted', 
			    'Pass Completion %', 'Passing Distance', 'Progressive Passing Distance', 
			    'Short Passes Completed', 'Short Passes Attempted', 'Short Pass Completion %', 
			    'Medium Passes Completed', 'Medium Passes Attempted', 'Medium Pass Completion %', 
			    'Long Passes Completed', 'Long Passes Attempted', 'Long Pass Completion %', 'Assists', 
			    'xA', 'Assists - xA', 'Key Passes', 'Passes into Final Third', 'Passes into Penalty Area', 
			    'Crosses into Penalty Area', 'Progressive Passes Completed', 'Open-play Passes', 'Dead-ball Passes', 
			    'Free-kick Passes', 'Throughballs', 'Passes under Pressure', 'Switches', 'Crosses', 'Corner Kicks', 
			    'Inswinging Corners', 'Outswinging Corners', 'Straight Corners', 'Ground Passes', 'Low Passes', 'High Passes', 
			    'Passes from Left Foot', 'Passes from Right Foot', 'Headed Passes', 'Throw-ins Taken', 'Passes from Other Bodypart', 
			    'Offside Passes', 'Out-of-bound Passes', 'Passes Intercepted', 'Passes Blocked', 
			    'Shot-creating Actions', 'Open-play Shot-creating Passes', 'Dead-ball Shot-creating Actions', 'Shot-creating Dribbles', 
			    'Shot-creating Shots', 'Shot-creating Actions Fouls Drawn', 'Shot-creating Defensive Actions', 'Goal-creating Actions', 
			    'Open-play Goal-creating Passes', 'Dead-ball Goal-creating Actions', 'Goal-creating Dribbles', 'Goal-creating Shots', 
			    'Goal-creating Fouls Drawn', 'Goal-creating Defensive Actions', 'Action leading to Opposition Own-goal', 'Tackles Attempted', 'Tackles Won', 
			    'Defensive Third Tackles', 'Middle Third Tackles', 'Final Third Tackles', 'Successful Tackles vs Dribblers', 
			    'Attempted Tackles vs Dribblers', 'Tackle success % vs Dribblers', 'Unsuccessful Tackles vs Dribblers', 
			    'Pressures', 'Successful Pressures', 'Pressure Success %', 'Defensive Third Pressures', 'Middle Third Pressures', 
			    'Final Third Pressures', 'Blocks', 'Shots Blocked', 'Shot on Target Blocked', 
			    'Clearances', 'Errors', 'Touches', 'Touches in Own Penalty Area', 
			    'Touches in Defensive Third', 'Touches in Middle Third', 'Touches in Attacking Third', 'Touches in Penalty Area', 
			    'Open-play Touches', 'Successful Dribbles', 'Attempted Dribbles', 'Dribble Success %', 'Number of Players Dribbled', 
			    'Nutmegs', 'Carries', 'Total Distance Carried', 'Progressive Distance Carried', 'Progressive Carries', 
			    'Carries into Final Third', 'Carries into Penalty Area', 'Times Misplaced', 'Times Dispossessed', 
			    'Attempted Ball Receipts', 'Successful Ball Receipts', 'Successful Ball Receipt %', 'Progressive Passes Received', 
			    'Yellow Cards', 'Red Cards', 'Second Yellow Cards', 'Fouls Committed', 'Fouls Drawn', 'Offsides', 'Interceptions', 
			    'Penalties Won', 'Penalties Conceded', 'Own-goals', 'Recoveries', 'Aerial Duels Won', 
			    'Aerial Duels Lost', 'Aerial Duels Success %'
			    ] 
"""note this does not have turnovers, open play shot creating actions and non-penalty goals but that's okay because 
I only need it the once"""

COUNT_STATS =   ['Goals', 'Shots', 'Shots on Target', 'Freekicks Attempted', 'Penalties Scored', 'Penalties Attempted',
				 'xG', 'Non-penalty xG', 'Goals - xG', 'Non-penalty Goals - Non-penalty xG', 'Non-penalty Goals', 
				 'Open-play Shot-creating Actions', 'Passes Completed', 'Passes Attempted', 'Passing Distance',
				 'Progressive Passing Distance', 'Short Passes Completed', 'Short Passes Attempted',
				 'Medium Passes Completed', 'Medium Passes Attempted', 'Turnovers',
				 'Long Passes Completed', 'Long Passes Attempted', 'Assists', 'xA', 'Assists - xA',
				 'Key Passes', 'Passes into Final Third', 'Passes into Penalty Area', 'Crosses into Penalty Area',
				 'Progressive Passes Completed', 'Open-play Passes', 'Dead-ball Passes', 'Free-kick Passes',
				 'Throughballs', 'Passes under Pressure', 'Switches', 'Crosses', 'Corner Kicks',
				 'Inswinging Corners', 'Outswinging Corners', 'Straight Corners', 'Ground Passes',
				 'Low Passes', 'High Passes', 'Passes from Left Foot', 'Passes from Right Foot',
				 'Headed Passes', 'Throw-ins Taken', 'Passes from Other Bodypart', 'Offside Passes',
				 'Out-of-bound Passes', 'Passes Intercepted', 'Passes Blocked', 'Shot-creating Actions',
				 'Open-play Shot-creating Passes', 'Dead-ball Shot-creating Actions', 'Shot-creating Dribbles',
				 'Shot-creating Shots', 'Shot-creating Actions Fouls Drawn', 'Shot-creating Defensive Actions',
				 'Goal-creating Actions', 'Open-play Goal-creating Passes', 'Dead-ball Goal-creating Actions',
				 'Goal-creating Dribbles', 'Goal-creating Shots', 'Goal-creating Fouls Drawn',
				 'Goal-creating Defensive Actions', 'Action leading to Opposition Own-goal',
				 'Tackles Attempted', 'Tackles Won', 'Defensive Third Tackles', 'Middle Third Tackles',
				 'Final Third Tackles', 'Successful Tackles vs Dribblers', 'Attempted Tackles vs Dribblers',
				 'Unsuccessful Tackles vs Dribblers', 'Pressures',
				 'Successful Pressures', 'Defensive Third Pressures', 'Middle Third Pressures',
				 'Final Third Pressures', 'Blocks', 'Shots Blocked', 'Shot on Target Blocked', 'Clearances', 'Errors',
				 'Touches', 'Touches in Own Penalty Area', 'Touches in Defensive Third', 'Touches in Middle Third',
				 'Touches in Attacking Third', 'Touches in Penalty Area', 'Open-play Touches', 'Successful Dribbles',
				 'Attempted Dribbles', 'Number of Players Dribbled', 'Nutmegs', 'Carries',
				 'Total Distance Carried', 'Progressive Distance Carried', 'Progressive Carries', 'Carries into Final Third',
				 'Carries into Penalty Area', 'Times Misplaced', 'Times Dispossessed', 'Attempted Ball Receipts',
				 'Successful Ball Receipts', 'Progressive Passes Received', 'Yellow Cards',
				 'Red Cards', 'Second Yellow Cards', 'Fouls Committed', 'Fouls Drawn', 'Offsides', 'Interceptions',
				 'Penalties Won', 'Penalties Conceded', 'Own-goals', 'Recoveries', 'Aerial Duels Won', 'Aerial Duels Lost'] 
				 ##to per 90-ify

TEMPLATES_DICT = {'DM/CM':  ['Tackles Attempted', 'Tackles Won', 'Interceptions', 'Successful Pressures',
                            'Turnovers', 'Successful Dribbles', 'Dribble Success %', 'Pass Completion %',  
                            'Progressive Passing Distance', 'Passes into Final Third', 'Open-play Shot-creating Actions'],

                  'CAM/WF': ['Non-penalty Goals', 'Non-penalty xG', 'Non-penalty xG/shot', 'xA',  
                             'Open-play Shot-creating Actions', 'Passes into Penalty Area', 'Progressive Passing Distance',  
                             'Pass Completion %', 'Successful Dribbles', 'Dribble Success %', 'Times Dispossessed', 
                             'Successful Pressures'],

                  'FB': ['xA', 'Passes into Penalty Area', 'Successful Dribbles', 'Dribble Success %', 
                         'Times Dispossessed', 'Successful Pressures', 'Interceptions', 'Tackles Won',
                         'Tackle success % vs Dribblers', 'Aerial Duels Success %'],

                  'CB': ['Passes into Final Third', 'Clearances', 'Aerial Duels Success %', 'Aerial Duels Won',
                         'Fouls Committed', 'Unsuccessful Tackles vs Dribblers', 'Tackles Won', 'Interceptions',
                         'Successful Pressures', 'Long Pass Completion %',  'Pass Completion %', 'Progressive Passing Distance'],

                  'FW': ['Successful Pressures', 'Turnovers', 'Successful Dribbles', 'Dribble Success %',
                         'xA', 'Passes into Penalty Area', 'Touches in Penalty Area', 'Aerial Duels Won', 'Aerial Duels Success %',
                         'Non-penalty Goals', 'Non-penalty xG', 'Non-penalty xG/shot']
                }
